# Generated by Django 3.2.7 on 2024-12-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+914567894567', max_length=12, region=None, verbose_name='Phone Numer')),
                ('about_me', models.CharField(default='Add something in the about me', max_length=250, verbose_name='About me')),
                ('profile_photo', models.ImageField(default='/default.png', upload_to='', verbose_name='Profile Picture')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='License details')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='OTHER', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='India', max_length=2, verbose_name='Country')),
                ('city', django_countries.fields.CountryField(default='Mumbai', max_length=2, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you a Buyer?', verbose_name='Buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you a Seller', verbose_name='Seller')),
                ('top_agent', models.BooleanField(default=False, help_text='Top Agent', verbose_name='Agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
